Projekt/AIProjekt/Controllers/AgregatorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity;
using AIProjekt.Domain;
using AIProjekt.Domain.DbModels;
using AIProjekt.Models.Agregator;
using Microsoft.AspNet.Identity;
using PagedList;

namespace AIProjekt.Controllers
{
    public class AgregatorController : Controller
    {
        public ActionResult Index(int page = 1)
        {
            const int pageSize = 2;

            using (ZakopContext context = new ZakopContext())
            {
                var posts = GetPostsFromDb(context);

                posts = posts.Where(p => p.PostiveRank > 1 && (float)p.PostiveRank / (p.NegativeRank + 1) > 0.25);

                PagedList<PostViewModel> model = new PagedList<PostViewModel>(posts, page, pageSize);

                return View(model);
            }
        }

        public ActionResult RisingIndex(int page = 1)
        {
            const int pageSize = 2;

            using (ZakopContext context = new ZakopContext())
            {
                var posts = GetPostsFromDb(context);

                posts = posts.Where(p => p.PostiveRank <= 1 || (float)p.PostiveRank / (p.NegativeRank + 1) <= 0.25);

                PagedList<PostViewModel> model = new PagedList<PostViewModel>(posts, page, pageSize);

                return View(model);
            }
        }

        private IEnumerable<PostViewModel> GetPostsFromDb(ZakopContext context)
        {
            string userId = User.Identity.GetUserId();
            IEnumerable<PostViewModel> posts = (from Post p in context.Posts
                .Include(p => p.User)
                .Include(p => p.Comments)
                .Include(p => p.PostUsers)
                orderby p.TimeAdded descending
                select new PostViewModel
                {
                    PostId = p.Id,
                    AuthorId = p.UserId,
                    Author = p.User.UserName,
                    PostiveRank = context.PostUsers
                        .Count(pu => pu.PostId == p.Id && pu.Digged == Digged.Digged),
                    NegativeRank = context.PostUsers
                        .Count(pu => pu.PostId == p.Id && pu.Digged == Digged.Buried)
                    ,
                    Digged = p.PostUsers
                        .Where(pu => pu.PostId == p.Id && pu.UserId == userId)
                        .Select(pu => pu.Digged)
                        .FirstOrDefault(),
                    CommentCount = p.Comments.Count,
                    Title = p.Title,
                    TimeAdded = p.TimeAdded,
                    Description = p.Description,
                    HasImage = p.Image != null
                }).ToList();
            return posts;
        }


        [Authorize]
        public ActionResult Digg(int postId)
        {
            using (ZakopContext context = new ZakopContext())
            {
                Post post = context.Posts.Include(p => p.PostUsers).SingleOrDefault(p => p.Id == postId);
                string userId = User.Identity.GetUserId();
                User user = context.Users.SingleOrDefault(u => u.Id == userId);

                if (post == null || post.UserId == user.Id)
                {
                    if (Request.IsAjaxRequest())
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    return View("Error");
                }

                PostUser postUser = post.PostUsers.SingleOrDefault(pu => pu.UserId == user.Id && pu.PostId == post.Id);

                if (postUser != null)
                {
                    switch (postUser.Digged)
                    {
                        case Digged.Digged:
                            postUser.Digged = null;
                            break;
                        case Digged.Buried:
                            postUser.Digged = Digged.Digged;
                            break;
                        default:
                            postUser.Digged = Digged.Digged;
                            break;
                    }
                }
                else
                {
                    postUser = new PostUser
                    {
                        Digged = Digged.Digged,
                        User = user,
                        Post = post
                    };

                    post.PostUsers.Add(postUser);
                }

                context.SaveChanges();

                if (Request.IsAjaxRequest())
                {
                    var dataToSend = new
                    {
                        postId = post.Id,
                        digged = postUser.Digged,
                        positiveRank = post.PostUsers.Count(pu => pu.Digged == Digged.Digged),
                        negativeRank = post.PostUsers.Count(pu => pu.Digged == Digged.Buried),
                    };
                    return Json(dataToSend, JsonRequestBehavior.AllowGet);
                }

                return RedirectToAction("Index", "Post", new { postId = post.Id });
            }
        }


        [Authorize]
        public ActionResult Bury(int postId)
        {
            using (ZakopContext context = new ZakopContext())
            {
                Post post = context.Posts.Include(p => p.PostUsers)
                    .Include(p => p.PostUsers)
                    .SingleOrDefault(p => p.Id == postId);
                string userId = User.Identity.GetUserId();
                User user = context.Users.SingleOrDefault(u => u.Id == userId);

                if (post == null || post.UserId == user.Id)
                {
                    if (Request.IsAjaxRequest())
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    return View("Error");
                }

                PostUser postUser = post.PostUsers.SingleOrDefault(pu => pu.UserId == user.Id && pu.PostId == post.Id);

                if (postUser != null)
                {
                    switch (postUser.Digged)
                    {
                        case Digged.Digged:
                            postUser.Digged = Digged.Buried;
                            break;
                        case Digged.Buried:
                            postUser.Digged = null;
                            break;
                        default:
                            postUser.Digged = Digged.Buried;
                            break;
                    }
                }
                else
                {
                    postUser = new PostUser
                    {
                        Digged = Digged.Buried,
                        User = user,
                        Post = post
                    };

                    post.PostUsers.Add(postUser);
                }

                context.SaveChanges();

                if (Request.IsAjaxRequest())
                {
                    var dataToSend = new
                    {
                        postId = post.Id,
                        digged = postUser.Digged,
                        positiveRank = post.PostUsers.Count(pu => pu.Digged == Digged.Digged),
                        negativeRank = post.PostUsers.Count(pu => pu.Digged == Digged.Buried),
                    };
                    return Json(dataToSend, JsonRequestBehavior.AllowGet);
                }

                return RedirectToAction("Index", "Post", new { postId = post.Id });
            }
        }

        public FileContentResult GetImage(int postId)
        {
            using (ZakopContext context = new ZakopContext())
            {
                Post post = context.Posts.FirstOrDefault(p => p.Id == postId);
                if (post != null)
                {
                    return new FileContentResult(post.Image, post.ContentType);
                }
                return null;
            }
        }
    }
}

Projekt/AIProjekt/Views/Shared/PostBar.cshtml
@using AIProjekt.Domain.DbModels
@using Microsoft.AspNet.Identity

@model AIProjekt.Models.Agregator.PostViewModel

@{
    AjaxOptions diggAjaxOptions = new AjaxOptions
    {
        Url = Url.Action("Digg", "Agregator"),
        AllowCache = false,
        HttpMethod = "Get",
        OnSuccess = "updateRank"
    };

    AjaxOptions buryAjaxOptions = new AjaxOptions
    {
        Url = Url.Action("Bury", "Agregator"),
        AllowCache = false,
        HttpMethod = "Get",
        OnSuccess = "updateRank"
    };
}


<div class="row agregator-post">
    <div class="col-md-1 text-center" id="@Model.PostId">
        @if (User.Identity.IsAuthenticated && Model.AuthorId == User.Identity.GetUserId())
        {
            <div class="text-center rank-text">
                @{
            int rank = Model.PostiveRank - Model.NegativeRank;
                }

                <div class="cumulated-rank">
                    @rank
                </div>

                <div class="separate-rank">
                    (
                    <span class="positive-rank">@Model.PostiveRank</span>
                    /
                    <span class="negative-rank">@Model.NegativeRank</span>
                    )
                </div>
            </div>
        }
        else
        {
            using (Ajax.BeginForm("Digg", "Agregator", diggAjaxOptions))
            {
                @Html.Hidden("postId", Model.PostId)
                <button class="btn @(Model.Digged == Digged.Digged ? "btn-default" : "btn-primary") dig" type="submit"><i class="glyphicon glyphicon-arrow-up"></i></button>
            }
            <div class="text-center rank-text">
                @{
            int rank = Model.PostiveRank - Model.NegativeRank;
                }

                <div class="cumulated-rank">
                    @rank
                </div>
                <div class="separate-rank">
                    (
                    <span class="positive-rank">@Model.PostiveRank</span>
                    /
                    <span class="negative-rank">@Model.NegativeRank</span>
                    )
                </div>
            </div>
            using (Ajax.BeginForm("Bury", "Agregator", buryAjaxOptions))
            {
                @Html.Hidden("postId", Model.PostId)
                <button class="btn @(Model.Digged == Digged.Buried ? "btn-default" : "btn-danger") bury" type="submit"><i class="glyphicon glyphicon-arrow-down"></i></button>
            }
        }

    </div>
    <div class="col-md-2">
        @if (Model.HasImage)
        {
            <img src='@Url.Action("GetImage", "Agregator", new { postId = Model.PostId })' class="image-icon" alt="@Model.ImageName"/>
        }
        else
        {
            <img class="image-icon" src="@Url.Content("~/Images/Z-image.jpg")" alt="default-image" />
        }
    </div>
    <div class="col-md-9">
        <h4>@Html.ActionLink(Model.Title, "Index", new { controller = "Post", postId = Model.PostId })</h4>
        <p>@Model.TimeAdded Dodane przez : @Model.Author</p>
        <p class="word-wrap">@Model.Description</p>

            @string.Format("Komentarze: {0}", Model.CommentCount)
    </div>
</div>

Projekt/AIProjekt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Główna", "Index", "Agregator")</li>
                    <li>@Html.ActionLink("Wykopalisko", "RisingIndex", "Agregator")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Nowy wykop", "NewPost", "Post")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="padding-10">
            @RenderBody()
        </div>

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Wojskowa Akademia Techniczna </p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Projekt/AIProjekt/Views/Shared/_LoadingGif.cshtml
<div class="windows8">
    <div class="wBall" id="wBall_1">
        <div class="wInnerBall">
        </div>
    </div>
    <div class="wBall" id="wBall_2">
        <div class="wInnerBall">
        </div>
    </div>
    <div class="wBall" id="wBall_3">
        <div class="wInnerBall">
        </div>
    </div>
    <div class="wBall" id="wBall_4">
        <div class="wInnerBall">
        </div>
    </div>
    <div class="wBall" id="wBall_5">
        <div class="wInnerBall">
        </div>
    </div>
</div>