Projekt/AIProjekt/Models/Agregator/NewPostViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;
using AIProjekt.Domain.CustomAttributes;

namespace AIProjekt.Models.Agregator
{
    public class NewPostViewModel
    {
        [DisplayName("Tytuł")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} jest wymagany")]
        [MaxLength(100, ErrorMessage = "{0} może mieć maksymalnie 100 znaków.")]
        public string Title { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} jest wymagany")]
        [MaxLength(200, ErrorMessage = "{0} może mieć maksymalnie 200 znaków.")]
        [DisplayName("Opis")]
        public string Description { get; set; }

        [DisplayName("Obrazek")]
        [ValidateFileSize(ErrorMessage = "Dozwolony rozmiar < 1MB")]
        [ValidateFileExtension(ErrorMessage = "Wymagany format: *.png , *.bmp, *.jpeg")]
        public HttpPostedFileBase File { get; set; }

        [DisplayName("Link do treści")]
        [LinkValidator(ErrorMessage = "Nieprawidłowy adres URL.")]
        public string Link { get; set; }

        [DisplayName("Treść")]
        public string Contents { get; set; }
    }
}

Projekt/AIProjekt/Models/Agregator/PostDetailViewModel.cs
using System.Collections.Generic;
using AIProjekt.Domain.DbModels;

namespace AIProjekt.Models.Agregator
{
    public class PostDetailViewModel : PostViewModel
    {
        public IEnumerable<Comment> Comments { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }

        public NewCommentViewModel NewComment { get; set; }
    }
}

Projekt/AIProjekt/Models/Agregator/PostViewModel.cs
using System;
using AIProjekt.Domain.DbModels;

namespace AIProjekt.Models.Agregator
{
    public class PostViewModel
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime TimeAdded { get; set; }
        public string AuthorId { get; set; }
        public string Author { get; set; }
        public int CommentCount { get; set; }

        public int PostiveRank { get; set; }
        public int NegativeRank { get; set; }

        public bool HasImage { get; set; }
        public string ImageName { get; set; }

        public Digged? Digged { get; set; }
    
    }
}

Projekt/AIProjekt/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AIProjekt.Domain;
using AIProjekt.Domain.DbModels;
using System.Data.Entity;
using AIProjekt.Models.Agregator;
using Microsoft.AspNet.Identity;

namespace AIProjekt.Controllers
{
    public class CommentController : Controller
    {
        [Authorize]
        [HttpPost]
        public ActionResult AddComment(NewCommentViewModel newComment)
        {
            if (!ModelState.IsValid)
            {
                var allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return Json(allErrors);
            }

            using (ZakopContext context = new ZakopContext())
            {
                Post post = context.Posts.Include(p => p.Comments).FirstOrDefault(p => p.Id == newComment.PostId);


                if (post == null)
                    return View("Error");

                string userId = User.Identity.GetUserId();
                User user = context.Users.FirstOrDefault(u => u.Id == userId);

                Comment comment = new Comment
                {
                    CommentDate = DateTime.Now,
                    Contents = newComment.Contents,
                    User = user,
                    Post = post
                };

                post.Comments.Add(comment);

                context.SaveChanges();

                IEnumerable<Comment> comments = post.Comments;

                return PartialView("CommentsPartial", comments);
            }
        }
    }
}

Projekt/AIProjekt/Controllers/PostController.cs
using System;
using System.Drawing;
using System.Web.Mvc;
using System.Linq;
using System.Data.Entity;
using AIProjekt.Domain;
using AIProjekt.Domain.DbModels;
using AIProjekt.Models.Agregator;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;

namespace AIProjekt.Controllers
{
    public class PostController : Controller
    {
        public ActionResult Index(int postId)
        {
            using (ZakopContext context = new ZakopContext())
            {
                string userId = User.Identity.GetUserId();

                PostDetailViewModel postDetails = (from p in context.Posts
                                                   where p.Id == postId
                                                   select new PostDetailViewModel
                                                   {
                                                       PostId = p.Id,
                                                       Title = p.Title,
                                                       Description = p.Description,
                                                       Content = p.Contents,
                                                       Link = p.Link,
                                                       AuthorId = p.UserId,
                                                       Author = p.User.UserName,
                                                       TimeAdded = p.TimeAdded,
                                                       CommentCount = p.Comments.Count,
                                                       ImageName = p.FileName,
                                                       HasImage = p.Image != null,
                                                       Digged = p.PostUsers.FirstOrDefault(pu => pu.UserId == userId).Digged,
                                                       PostiveRank = context.PostUsers
                                                                     .Count(pu => pu.PostId == p.Id && pu.Digged == Digged.Digged),
                                                       NegativeRank = context.PostUsers
                                                              .Count(pu => pu.PostId == p.Id && pu.Digged == Digged.Buried)
                                                   })
                    .SingleOrDefault();

                if (postDetails == null)
                    return View("Error");

                postDetails.Comments =
                    context.Comments.Include(c => c.User)
                        .Where(c => c.PostId == postDetails.PostId)
                        .OrderByDescending(c => c.CommentDate)
                        .ToArray();

                if (!postDetails.Content.IsNullOrWhiteSpace())
                    postDetails.Content = postDetails.Content.Replace("\n", "<br />");

                return View("PostDetails", postDetails);
            }
        }


        public ActionResult NewPost()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult NewPost(NewPostViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.Contents.IsNullOrWhiteSpace() && model.Link.IsNullOrWhiteSpace())
                ModelState.AddModelError("NullContents", "Link lub Zawartość nie może być pusta.");

            if (model.File != null && model.File.ContentLength > 0)
            {
                try
                {
                    Image.FromStream(model.File.InputStream);
                    model.File.InputStream.Position = 0;
                    //valid input
                }
                catch
                {
                    ModelState.AddModelError("Image", "Nieprawidłowy format obrazka.");
                }
            }

            if (!ModelState.IsValid)
                return View(model);

            Post post = new Post
            {
                Title = model.Title,
                Description = model.Description,
                Contents = model.Contents,
                Link = model.Link,
                TimeAdded = DateTime.Now,
                Rank = 0
            };

            if (model.File != null && model.File.ContentLength > 0)
            {
                post.FileName = model.File.FileName;
                post.ContentType = model.File.ContentType;

                byte[] fileContent = new byte[model.File.ContentLength];
                model.File.InputStream.Read(fileContent, 0, model.File.ContentLength);

                post.Image = fileContent;
            }

            string userId = User.Identity.GetUserId();

            using (ZakopContext context = new ZakopContext())
            {
                User user = context.Users.FirstOrDefault(u => u.Id == userId);
                post.User = user;
                context.Posts.Add(post);
                context.SaveChanges();
            }

            return RedirectToAction("Index", "Post", new { postId = post.Id });
        }
    }
}

Projekt/AIProjekt/Views/Post/NewCommentPartial.cshtml
@model AIProjekt.Models.Agregator.NewCommentViewModel

@{
    AjaxOptions newCommentAjaxOptions = new AjaxOptions
    {
        Url = Url.Action("AddComment", "Comment"),
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        LoadingElementDuration = 1000,
        LoadingElementId = "comment-loading",
        AllowCache = false,
        UpdateTargetId = "comments-container"
    };

}

@using (Ajax.BeginForm(null, null, newCommentAjaxOptions, new { @class = "form-group form-max-width", id = "new-comment-form" }))
{
    @Html.HiddenFor(m => m.PostId)
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            @Html.TextAreaFor(m => m.Contents, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Contents, null, new { @class = "text-danger" })
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="col-md-12 text-center padding-10">
        <div class="col-lg-offset-5 col-md-1 ">
            <input type="submit" class="btn btn-primary" value="Opublikuj" />
        </div>
        <span id="comment-loading" class="col-md-1" style="display: none;">@Html.Partial("_LoadingGif")</span>
        <div class="col-md-5"></div>
    </div>
}

Projekt/AIProjekt/Views/Post/NewPost.cshtml
@model AIProjekt.Models.Agregator.NewPostViewModel

@{
    ViewBag.Title = "Nowy wykop";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div clas="row">
    <hr />
    @using (Html.BeginForm("NewPost", "Post", FormMethod.Post, new { @class = "form-horizontal form-max-width", role = "form", id = "new-post-form", enctype = "multipart/form-data" }))
    {
        <fieldset>
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Description, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Link, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Link, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Link, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Contents, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(m => m.Contents, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Contents, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.File, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    <input type="file" name="File" accept="image/*" />
                    @Html.ValidationMessageFor(m => m.File, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-2 col-lg-offset-2">
                    <input type="submit" class="btn btn-primary" value="Dodaj" />
                </div>
            </div>
        </fieldset>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("#new-post-form").submit(function (e) {
            var form = $('#new-post-form');

            var link = $('#Link', form);
            var contents = $('#Contents', form);

            if (link.val() === "" && contents.val() === "") {
                alert('Link lub Treść musi zostać wypełniona.');
                return false;
            }

            return true;
        });
    </script>
}

Projekt/AIProjekt/Views/Post/PostDetails.cshtml
@using AIProjekt.Domain.HtmlExtenstions
@using AIProjekt.Models.Agregator
@model PostDetailViewModel

@{
    ViewBag.Title = Model.Title + " - Zakop";
    Layout = "../Shared/_Layout.cshtml";

    bool isYtLink = false;
    if (Model.Link != null)
    {
        isYtLink = Html.IsValidYoutubeAddress(Model.Link);
    }
}

@{
    Html.RenderPartial("PostBar", Model);
}
<hr />
@if (isYtLink)
{
    <div class="row">
        <div class="col-md-12 text-center">
            <div id="yt-player" class="padding-30"></div>
        </div>
    </div>
}

<ul class="nav nav-tabs">
    @if (Model.Link != null && !isYtLink)
    {
        <li class="active">
            <a href="#link" data-toggle="tab">Link</a>
        </li>
    }

    @if (Model.Content != null)
    {
        <li class="@(Model.Link == null ? "active" : "")">
            <a href="#content" data-toggle="tab">Treść</a>
        </li>
    }
    <li class="@(Model.Content == null && isYtLink ? "active" : "")">
        <a href="#comments" data-toggle="tab">Komentarze ( @(Model.Comments.Any() ? Model.CommentCount : 0) )</a>
    </li>
</ul>

<div class="tab-content">

    @if (Model.Link != null && !isYtLink)
    {
        <div class="tab-pane fade in active" id="link">
            <div class="padding-20 link-text">
                <a href="@Model.Link" target="_blank">@Model.Link</a>
            </div>
        </div>
    }

    @if (Model.Content != null)
    {
        <div class="tab-pane fade in @(Model.Link == null ? "active" : "")" id="content">
            <div class="padding-20">
                <p>@Html.Raw(Model.Content)</p>
            </div>
        </div>
    }

    <div class="tab-pane fade in  @(Model.Content == null && isYtLink ? "active" : "")" id="comments">
        <div class="row padding-20">
            @if (User.Identity.IsAuthenticated)
            {
                <div class="col-md-12">
                    @{ Html.RenderPartial("NewCommentPartial", new NewCommentViewModel { PostId = Model.PostId });}
                </div>
            }
            <div class="col-md-offset-2 col-md-8" id="comments-container">
                @Html.Partial("~/Views/Comment/CommentsPartial.cshtml", Model.Comments)
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>


@section scripts
{
    <script src="~/Scripts/MyScripts/digBuryScript.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        var tag = document.createElement('script');
        tag.src = "https://www.youtube.com/player_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        var player;
        function onYouTubePlayerAPIReady() {
            player = new YT.Player('yt-player', {
                height: '390',
                width: '640',
                videoId: "@(isYtLink ? Html.GetVideoIdFromYoutubeLink(Model.Link) : "")"
            });
        }

    </script>

    <script>
        ResetUnobtrusiveValidation($('#new-comment-form'));
    </script>
}